# Generated by Django 4.1.12 on 2023-12-16 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdii_app', '0003_alter_aluno_table_alter_cliente_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aluno',
            new_name='Utilizador',
        ),
    ]
