# Generated by Django 4.1.12 on 2023-12-16 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdii_app', '0004_rename_aluno_utilizador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Utilizador',
        ),
    ]
