# Generated by Django 4.1.12 on 2023-12-17 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdii_app', '0005_remove_utilizador_user_delete_customuser_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
    ]
