# Generated by Django 4.1.12 on 2023-12-19 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdii_app', '0007_armazem_equipamento_delete_componente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armazem',
            options={},
        ),
        migrations.AlterModelTable(
            name='equipamento',
            table='equipamento',
        ),
    ]
