# Generated by Django 4.1.12 on 2023-12-19 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdii_app', '0008_alter_armazem_options_alter_equipamento_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='armazem',
            table='armazem',
        ),
    ]
