# Generated by Django 4.1.12 on 2023-12-19 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdii_app', '0009_alter_armazem_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armazem',
            old_name='data_saida',
            new_name='data_saidaa',
        ),
    ]
