# Generated by Django 4.1.12 on 2023-12-19 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdii_app', '0010_rename_data_saida_armazem_data_saidaa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armazem',
            old_name='data_saidaa',
            new_name='data_saida',
        ),
    ]
