# Generated by Django 4.1.12 on 2023-12-19 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdii_app', '0011_rename_data_saidaa_armazem_data_saida'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='armazem',
            table='Armazem',
        ),
    ]
